import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ShopContextProvider from "@/context/ShopContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SearchBar from "@/components/SearchBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ShopContextProvider>
          <ToastContainer />
          <Navbar />
          <SearchBar/>
          <main className="px-4 sm:px-8 lg:px-16">
            {children}
          </main>
          <Footer />
        </ShopContextProvider>
      </body>
    </html>
  );
}